# ===== General settings =====
model:
  name: "mistral:latest"
  device: "auto"

# ===== Memory / Replay Buffer =====
memory:
  max_size: 10000
  storage_path: "./memory_store"

# ===== Training / Fine-tuning =====
trainer:
  batch_size: 32
  learning_rate: 1e-4
  num_epochs: 5
  self_improve_threshold: 100

# ===== Logging =====
logging:
  log_dir: "./logs"
  level: "INFO"
